/**
 * ÉLÉGANCE - FASHION E-COMMERCE PRODUCT DATASET
 * 80 Premium Realistic Demo Fashion Products with High-Res Unsplash Photography
 * Exactly 10+ items per category: Dresses, Outerwear, Shirts, Knitwear, Pants, Bags, Shoes, Accessories
 */

const PRODUCTS_DATA = [
  // ==================== 1. DRESSES (10 items) ====================
  {
    id: 101,
    name: "Silk Wrap Midi Dress",
    category: "dresses",
    gender: "women",
    price: 189.00,
    originalPrice: 240.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Midnight Black", "Champagne"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviewCount: 42,
    description: "Tailored from 100% pure mulberry silk, this wrap dress features an asymmetric drape, defined waist tie, and elegant midi hemline perfect for evening occasions.",
    material: "100% Mulberry Silk",
    careInstructions: "Dry clean only. Cool iron on reverse.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 102,
    name: "Satin Evening Slip Dress",
    category: "dresses",
    gender: "women",
    price: 165.00,
    originalPrice: 210.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80"],
    colors: ["Magenta", "Emerald", "Champagne"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 54,
    description: "Floor-sweeping bias-cut satin gown with cowled neckline and adjustable delicate shoulder straps.",
    material: "97% Polyester Satin, 3% Elastane",
    careInstructions: "Hand wash cold or dry clean.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 103,
    name: "Floral Chiffon Maxi Dress",
    category: "dresses",
    gender: "women",
    price: 175.00,
    originalPrice: 220.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80"],
    colors: ["Dusty Floral", "Navy Rose"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 38,
    description: "Ethereal floral printed chiffon maxi dress featuring sheer long sleeves, smocked waist, and tiered skirt.",
    material: "100% Recycled Chiffon",
    careInstructions: "Machine wash delicate cold.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 104,
    name: "Velvet Off-Shoulder Cocktail Dress",
    category: "dresses",
    gender: "women",
    price: 210.00,
    originalPrice: 270.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80"],
    colors: ["Deep Burgundy", "Midnight Blue", "Onyx Black"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 61,
    description: "Plush silk-blend velvet cocktail dress crafted with a folded off-shoulder neckline and body-con silhouette.",
    material: "80% Rayon, 20% Silk Velvet",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 105,
    name: "Linen Button-Front Summer Dress",
    category: "dresses",
    gender: "women",
    price: 135.00,
    originalPrice: 170.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Ivory White", "Sage Green", "Soft Ochre"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 29,
    description: "Breezy pure linen midi dress styled with tortoise-shell buttons, removable belt, and side seam pockets.",
    material: "100% French Linen",
    careInstructions: "Machine wash warm, hang to dry.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 106,
    name: "Embroidered Tiered Boho Dress",
    category: "dresses",
    gender: "women",
    price: 155.00,
    originalPrice: 195.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Terracotta"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviewCount: 45,
    description: "Intricately embroidered cotton voile dress cut with balloon sleeves and a relaxed tiered midi skirt.",
    material: "100% Organic Cotton",
    careInstructions: "Hand wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 107,
    name: "Plunging V-Neck Satin Gown",
    category: "dresses",
    gender: "women",
    price: 245.00,
    originalPrice: 310.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1550639525-c97d455acf70?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold", "Emerald", "Navy"],
    sizes: ["XS", "S", "M", "L"],
    rating: 5.0,
    reviewCount: 72,
    description: "Glamorous red-carpet evening gown with deep V-cut neckline, open back, and sweeping thigh-high slit.",
    material: "100% Heavy Silk Satin",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 108,
    name: "Ribbed Knit Bodycon Dress",
    category: "dresses",
    gender: "women",
    price: 128.00,
    originalPrice: 160.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=800&auto=format&fit=crop&q=80"],
    colors: ["Camel", "Charcoal", "Cream"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviewCount: 33,
    description: "Form-fitting ribbed merino wool blend dress with high neckline and long sleeves for sophisticated autumn styling.",
    material: "70% Merino Wool, 30% Cashmere",
    careInstructions: "Hand wash cold, dry flat.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 109,
    name: "Pleated Georgette A-Line Dress",
    category: "dresses",
    gender: "women",
    price: 168.00,
    originalPrice: 210.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=800&auto=format&fit=crop&q=80"],
    colors: ["Powder Blue", "Blush Pink"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 50,
    description: "Graceful accordion-pleated midi dress featuring cap sleeves and a crystalline jewel button closure.",
    material: "100% Polyester Georgette",
    careInstructions: "Dry clean only.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 110,
    name: "Asymmetric Draped Silk Gown",
    category: "dresses",
    gender: "women",
    price: 260.00,
    originalPrice: 330.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=800&auto=format&fit=crop&q=80"],
    colors: ["Champagne", "Black"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 41,
    description: "Sculptural one-shoulder evening dress with a cascading side train and concealed invisible zip.",
    material: "100% Mulberry Silk Crepe",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },

  // ==================== 2. OUTERWEAR (10 items) ====================
  {
    id: 201,
    name: "Tailored Double-Breasted Blazer",
    category: "outerwear",
    gender: "women",
    price: 220.00,
    originalPrice: 280.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=800&auto=format&fit=crop&q=80"],
    colors: ["Powder Pink", "Ivory", "Classic Navy"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviewCount: 29,
    description: "Structured wool-blend blazer featuring horn buttons, sharp lapels, and functional flap pockets.",
    material: "70% Wool, 30% Silk Blend",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 202,
    name: "Classic Wool Trench Coat",
    category: "outerwear",
    gender: "men",
    price: 275.00,
    originalPrice: 350.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80"],
    colors: ["Beige", "Black", "Charcoal"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
    reviewCount: 31,
    description: "Timeless double-breasted trench coat with waist belt, epaulettes, and weather-resistant wool gabardine.",
    material: "100% Virgin Wool",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 203,
    name: "Structured Italian Linen Suit Jacket",
    category: "outerwear",
    gender: "men",
    price: 310.00,
    originalPrice: 390.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80"],
    colors: ["Dusty Pink", "Sand", "Navy"],
    sizes: ["38R", "40R", "42R", "44R"],
    rating: 4.8,
    reviewCount: 22,
    description: "Lightweight unstructured linen jacket tailored with notch lapels, double vents, and satin lining.",
    material: "100% Italian Linen",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 204,
    name: "Cropped Denim Trucker Jacket",
    category: "outerwear",
    gender: "women",
    price: 130.00,
    originalPrice: 160.00,
    discount: 18,
    images: ["https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=800&auto=format&fit=crop&q=80"],
    colors: ["Vintage Wash", "Light Pink Wash"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviewCount: 33,
    description: "Classic trucker style cropped jacket cut from rigid organic cotton denim with custom branded shank buttons.",
    material: "100% Organic Denim",
    careInstructions: "Machine wash cold inside out.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 205,
    name: "Faux Shearling Oversized Coat",
    category: "outerwear",
    gender: "women",
    price: 260.00,
    originalPrice: 320.00,
    discount: 18,
    images: ["https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&auto=format&fit=crop&q=80"],
    colors: ["Cream", "Chestnut"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviewCount: 58,
    description: "Plush faux shearling longline coat with exaggerated notch lapels and deep side slip pockets.",
    material: "100% Polyester Shearling",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 206,
    name: "Belted Camel Wool Long Coat",
    category: "outerwear",
    gender: "women",
    price: 340.00,
    originalPrice: 420.00,
    discount: 19,
    images: ["https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80"],
    colors: ["Classic Camel", "Onyx Black"],
    sizes: ["XS", "S", "M", "L"],
    rating: 5.0,
    reviewCount: 89,
    description: "Hand-finished double-faced camel wool wrap coat with self-tie belt and wide notched collar.",
    material: "100% Pure Wool",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 207,
    name: "Minimalist Biker Leather Jacket",
    category: "outerwear",
    gender: "unisex",
    price: 380.00,
    originalPrice: 480.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black", "Dark Espresso"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviewCount: 67,
    description: "Supple lambskin leather motorcycle jacket styled with silver hardware, asymmetrical zip, and zip cuffs.",
    material: "100% Genuine Lambskin Leather",
    careInstructions: "Specialist leather clean only.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 208,
    name: "Quilted Puffer Winter Jacket",
    category: "outerwear",
    gender: "women",
    price: 215.00,
    originalPrice: 270.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Quartz", "Matte Black"],
    sizes: ["S", "M", "L"],
    rating: 4.6,
    reviewCount: 42,
    description: "Water-repellent short puffer jacket filled with eco-down insulation and featuring a detachable hood.",
    material: "100% Recycled Nylon Shell",
    careInstructions: "Machine wash cold gentle.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 209,
    name: "Plaid Tweed Houndstooth Blazer",
    category: "outerwear",
    gender: "women",
    price: 235.00,
    originalPrice: 295.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black & White Houndstooth"],
    sizes: ["S", "M", "L"],
    rating: 4.7,
    reviewCount: 36,
    description: "Heritage houndstooth tweed blazer finished with fringe trimmings and embossed crest gold buttons.",
    material: "65% Wool, 35% Acrylic Tweed",
    careInstructions: "Dry clean only.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 210,
    name: "Lightweight Windbreaker Trench",
    category: "outerwear",
    gender: "men",
    price: 190.00,
    originalPrice: 240.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800&auto=format&fit=crop&q=80"],
    colors: ["Olive Green", "Charcoal"],
    sizes: ["M", "L", "XL"],
    rating: 4.5,
    reviewCount: 28,
    description: "Modern minimalist rain trench jacket crafted from technical water-resistant fabric with concealed snap buttons.",
    material: "100% Water-Resistant Polyester",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },

  // ==================== 3. SHIRTS (10 items) ====================
  {
    id: 301,
    name: "Slim Fit Oxford Cotton Shirt",
    category: "shirts",
    gender: "men",
    price: 85.00,
    originalPrice: 110.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80"],
    colors: ["Soft Pink", "Light Blue", "Crisp White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 94,
    description: "Breathable organic cotton oxford shirt tailored with button-down collar and mother-of-pearl buttons.",
    material: "100% Organic Cotton",
    careInstructions: "Machine wash warm, tumble dry low.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 302,
    name: "Pure Silk Button-Down Blouse",
    category: "shirts",
    gender: "women",
    price: 145.00,
    originalPrice: 180.00,
    discount: 19,
    images: ["https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Ivory White", "Champagne"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 68,
    description: "Lustrous crepe de chine silk blouse styled with French cuffs and a pointed shirt collar.",
    material: "100% Silk Crepe de Chine",
    careInstructions: "Dry clean or hand wash cold.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 303,
    name: "Linen Casual Short-Sleeve Shirt",
    category: "shirts",
    gender: "men",
    price: 78.00,
    originalPrice: 98.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80"],
    colors: ["Sand Beige", "Sage", "Sky Blue"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 44,
    description: "Relaxed resort-collar short sleeve shirt garment-washed for lightweight summer breathability.",
    material: "100% Pure Linen",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 304,
    name: "Satin Tie-Neck Designer Top",
    category: "shirts",
    gender: "women",
    price: 130.00,
    originalPrice: 165.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold", "Midnight Blue"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviewCount: 37,
    description: "Elegant satin blouse featuring an adjustable lavallière bow neck tie and pleated shoulder accents.",
    material: "95% Polyester Satin, 5% Elastane",
    careInstructions: "Hand wash cold.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 305,
    name: "Striped Poplin Oversized Shirt",
    category: "shirts",
    gender: "women",
    price: 95.00,
    originalPrice: 120.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blue & White Stripe", "Pink Stripe"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviewCount: 52,
    description: "Relaxed boyfriend-fit poplin shirt crafted with high-low hem and sharp chest patch pocket.",
    material: "100% Crisp Cotton Poplin",
    careInstructions: "Machine wash warm.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 306,
    name: "Ribbed Cotton Essential Tee",
    category: "shirts",
    gender: "unisex",
    price: 45.00,
    originalPrice: 60.00,
    discount: 25,
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80"],
    colors: ["Optic White", "Heather Grey", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.5,
    reviewCount: 88,
    description: "Premium heavy-weight organic combed cotton t-shirt with durable rib crew neck and twin-needle stitching.",
    material: "100% Combed Organic Cotton",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 307,
    name: "Lace-Trim Cami Silk Top",
    category: "shirts",
    gender: "women",
    price: 88.00,
    originalPrice: 110.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Black", "Ivory"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviewCount: 41,
    description: "Delicate silk camisole styled with eyelash Chantilly lace trimming along the neckline and spaghetti straps.",
    material: "100% Silk Charmeuse",
    careInstructions: "Hand wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 308,
    name: "Classic Denim Western Shirt",
    category: "shirts",
    gender: "men",
    price: 92.00,
    originalPrice: 115.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80"],
    colors: ["Indigowash Blue"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 31,
    description: "Authentic Western denim shirt styled with pearl snap buttons, curved shoulder yokes, and twin chest flap pockets.",
    material: "100% Cotton Denim",
    careInstructions: "Machine wash cold inside out.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 309,
    name: "Mandarin Collar Casual Shirt",
    category: "shirts",
    gender: "men",
    price: 82.00,
    originalPrice: 105.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1563630423918-b58f07336ac9?w=800&auto=format&fit=crop&q=80"],
    colors: ["White", "Navy Blue"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 26,
    description: "Clean band-collar linen-cotton shirt with concealed placket and tailored curved hemline.",
    material: "55% Linen, 45% Cotton",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 310,
    name: "Printed Hawaiian Viscose Shirt",
    category: "shirts",
    gender: "men",
    price: 75.00,
    originalPrice: 95.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80"],
    colors: ["Tropical Pink / Navy"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
    reviewCount: 19,
    description: "Silky lightweight camp-collar shirt with vibrant botanical print for relaxed holiday style.",
    material: "100% Eco-Viscose",
    careInstructions: "Machine wash cold gentle.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },

  // ==================== 4. KNITWEAR (10 items) ====================
  {
    id: 401,
    name: "Cashmere Oversized Sweater",
    category: "knitwear",
    gender: "women",
    price: 145.00,
    originalPrice: 185.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Soft", "Off White", "Camel"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviewCount: 68,
    description: "Luxuriously soft Mongolian cashmere knit sweater with a relaxed crew neck and ribbed trim accents.",
    material: "100% Mongolian Cashmere",
    careInstructions: "Hand wash cold with wool detergent. Lay flat to dry.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 402,
    name: "Merino Wool Crewneck Sweater",
    category: "knitwear",
    gender: "men",
    price: 125.00,
    originalPrice: 160.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rosewood", "Grey Melange", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 47,
    description: "Extra-fine merino wool pullover offering thermal comfort, ribbed cuffs, and sophisticated texture.",
    material: "100% Extra-fine Merino Wool",
    careInstructions: "Hand wash cold, dry flat.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 403,
    name: "Cable-Knit Chunky Cardigan",
    category: "knitwear",
    gender: "women",
    price: 160.00,
    originalPrice: 200.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&auto=format&fit=crop&q=80"],
    colors: ["Cream Oat", "Dusty Pink"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviewCount: 53,
    description: "Hand-knit chunky cable knit cardigan styled with horn button front closure and patch pockets.",
    material: "80% Wool, 20% Alpaca",
    careInstructions: "Hand wash cold, lay flat to dry.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 404,
    name: "Ribbed Turtleneck Wool Pullover",
    category: "knitwear",
    gender: "women",
    price: 135.00,
    originalPrice: 170.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80"],
    colors: ["Beige", "Black", "Charcoal"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviewCount: 39,
    description: "Cozy folded turtleneck sweater knitted from super-soft Australian lambswool.",
    material: "100% Lambswool",
    careInstructions: "Hand wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 405,
    name: "Cropped Alpaca Blend Jumper",
    category: "knitwear",
    gender: "women",
    price: 140.00,
    originalPrice: 175.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Sage"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviewCount: 31,
    description: "Lightweight fuzzy cropped jumper featuring drop shoulders and relaxed wide sleeves.",
    material: "50% Baby Alpaca, 50% Wool",
    careInstructions: "Dry clean only.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 406,
    name: "V-Neck Cashmere Knit Vest",
    category: "knitwear",
    gender: "unisex",
    price: 110.00,
    originalPrice: 140.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80"],
    colors: ["Ivory", "Navy", "Camel"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 27,
    description: "Preppy deep V-neck sleeveless sweater vest knitted in 100% cashmere for effortless layering.",
    material: "100% Cashmere",
    careInstructions: "Hand wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 407,
    name: "Patterned Nordic Wool Sweater",
    category: "knitwear",
    gender: "men",
    price: 150.00,
    originalPrice: 190.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?w=800&auto=format&fit=crop&q=80"],
    colors: ["Grey & White Fairisle"],
    sizes: ["M", "L", "XL"],
    rating: 4.9,
    reviewCount: 44,
    description: "Traditional Fair Isle jacquard motif jumper knitted from heavy insulating Icelandic wool yarn.",
    material: "100% Icelandic Pure Wool",
    careInstructions: "Hand wash cold.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 408,
    name: "Fine-Gauge Silk-Wool Cardigan",
    category: "knitwear",
    gender: "women",
    price: 155.00,
    originalPrice: 195.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Soft", "Pearl Gray"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviewCount: 36,
    description: "Sleek button-down fine knit cardigan trimmed with mother-of-pearl buttons.",
    material: "70% Silk, 30% Merino Wool",
    careInstructions: "Dry clean only.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 409,
    name: "Mock-Neck Ribbed Knit Top",
    category: "knitwear",
    gender: "women",
    price: 98.00,
    originalPrice: 125.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black", "Cream", "Taupe"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviewCount: 22,
    description: "Fitted short-sleeve sweater featuring a seamless mock neck cut in stretchy ribbed knit cotton.",
    material: "90% Cotton, 10% Elastane",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 410,
    name: "Open-Front Draped Long Knit",
    category: "knitwear",
    gender: "women",
    price: 170.00,
    originalPrice: 215.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80"],
    colors: ["Camel", "Charcoal"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviewCount: 48,
    description: "Floor-length duster cardigan with shawl collar and ribbed patch pockets.",
    material: "60% Wool, 40% Viscose",
    careInstructions: "Hand wash cold.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },

  // ==================== 5. PANTS (10 items) ====================
  {
    id: 501,
    name: "High-Waisted Pleated Trousers",
    category: "pants",
    gender: "women",
    price: 110.00,
    originalPrice: 140.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80"],
    colors: ["Dusty Rose", "Cream", "Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 35,
    description: "Flowy wide-leg trousers designed with front darts, high rise, and concealed front zip closure.",
    material: "95% Crepe Viscose, 5% Elastane",
    careInstructions: "Machine wash cold gentle cycle.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 502,
    name: "Chino Slim Fit Stretch Pants",
    category: "pants",
    gender: "men",
    price: 98.00,
    originalPrice: 125.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&auto=format&fit=crop&q=80"],
    colors: ["Stone Beige", "Dusty Pink", "Navy"],
    sizes: ["30", "32", "34", "36"],
    rating: 4.7,
    reviewCount: 61,
    description: "Versatile stretch-twill chinos engineered for maximum movement and sharp tailored silhouette.",
    material: "98% Cotton, 2% Elastane",
    careInstructions: "Machine wash cold with like colors.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 503,
    name: "Straight-Leg Raw Denim Jeans",
    category: "pants",
    gender: "unisex",
    price: 120.00,
    originalPrice: 150.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80"],
    colors: ["Dark Indigo Wash", "Black Denim"],
    sizes: ["28", "30", "32", "34", "36"],
    rating: 4.8,
    reviewCount: 74,
    description: "Selvedge denim jeans cut in a vintage straight fit with copper rivets and button fly.",
    material: "100% Organic Japanese Cotton Denim",
    careInstructions: "Machine wash cold inside out.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 504,
    name: "Wide-Leg Tailored Wool Pants",
    category: "pants",
    gender: "women",
    price: 145.00,
    originalPrice: 185.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80"],
    colors: ["Oatmeal", "Black", "Camel"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 42,
    description: "Fluid double-pleated wool trousers tailored with high waist band and deep slant pockets.",
    material: "100% Fine Italian Wool",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 505,
    name: "Tapered Linen Summer Trousers",
    category: "pants",
    gender: "women",
    price: 105.00,
    originalPrice: 135.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80"],
    colors: ["Off White", "Olive"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviewCount: 29,
    description: "Breathable ankle-length linen pants styled with drawstring elasticated waistband.",
    material: "100% Linen",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 506,
    name: "Cargo Utility Cotton Pants",
    category: "pants",
    gender: "men",
    price: 115.00,
    originalPrice: 145.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80"],
    colors: ["Khaki", "Charcoal"],
    sizes: ["30", "32", "34", "36"],
    rating: 4.6,
    reviewCount: 38,
    description: "Modern slim-fit cargo pants featuring side flap pockets and reinforced knee panels.",
    material: "97% Cotton Twill, 3% Elastane",
    careInstructions: "Machine wash warm.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 507,
    name: "Slim-Fit Leather Pants",
    category: "pants",
    gender: "women",
    price: 260.00,
    originalPrice: 320.00,
    discount: 18,
    images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black Leather"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 51,
    description: "Sleek stretch-lambskin pants designed with comfortable high rise and zip ankle cuffs.",
    material: "100% Genuine Lambskin",
    careInstructions: "Specialist leather clean.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 508,
    name: "Cropped Ankle Wool Slacks",
    category: "pants",
    gender: "men",
    price: 130.00,
    originalPrice: 165.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop&q=80"],
    colors: ["Charcoal Grey", "Navy"],
    sizes: ["30", "32", "34", "36"],
    rating: 4.7,
    reviewCount: 33,
    description: "Crisp cropped suit trousers tailored with sharp center creases and cuffed hems.",
    material: "80% Wool, 20% Polyester",
    careInstructions: "Dry clean only.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 509,
    name: "High-Rise Vintage Mom Jeans",
    category: "pants",
    gender: "women",
    price: 115.00,
    originalPrice: 145.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=800&auto=format&fit=crop&q=80"],
    colors: ["Light Vintage Wash"],
    sizes: ["25", "26", "27", "28", "29", "30"],
    rating: 4.8,
    reviewCount: 65,
    description: "Iconic 90s-inspired tapered jeans with snug waist fit and authentic rigid denim feel.",
    material: "100% Cotton Denim",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 510,
    name: "Relaxed Drawstring Jogger Pants",
    category: "pants",
    gender: "unisex",
    price: 88.00,
    originalPrice: 110.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop&q=80"],
    colors: ["Grey Melange", "Black", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 47,
    description: "Ultra-soft French terry fleece sweatpants with cuffed ankles and metal-tipped drawstring.",
    material: "100% Organic French Terry Cotton",
    careInstructions: "Machine wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },

  // ==================== 6. BAGS (10 items) ====================
  {
    id: 601,
    name: "Quilted Leather Shoulder Bag",
    category: "bags",
    gender: "women",
    price: 290.00,
    originalPrice: 350.00,
    discount: 17,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Black Gold", "Taupe"],
    sizes: ["One Size"],
    rating: 5.0,
    reviewCount: 88,
    description: "Handcrafted calfskin leather handbag with gold chain strap, twist lock closure, and micro-suede interior lining.",
    material: "100% Genuine Nappa Leather",
    careInstructions: "Wipe clean with soft leather conditioner.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 602,
    name: "Minimalist Leather Tote Bag",
    category: "bags",
    gender: "women",
    price: 240.00,
    originalPrice: 300.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80"],
    colors: ["Soft Rose", "Caramel", "Black"],
    sizes: ["Large"],
    rating: 4.8,
    reviewCount: 92,
    description: "Spacious everyday tote with laptop sleeve, magnetic closure, and reinforced shoulder straps.",
    material: "Full-Grain Italian Leather",
    careInstructions: "Condition regularly.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 603,
    name: "Structured Leather Crossbody Bag",
    category: "bags",
    gender: "women",
    price: 195.00,
    originalPrice: 245.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80"],
    colors: ["Burgundy", "Cognac", "Black"],
    sizes: ["Medium"],
    rating: 4.7,
    reviewCount: 49,
    description: "Compact saddle-style crossbody bag handcrafted in textured pebble leather with adjustable leather strap.",
    material: "Pebbled Italian Leather",
    careInstructions: "Wipe clean.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 604,
    name: "Satin Evening Clutch Purse",
    category: "bags",
    gender: "women",
    price: 135.00,
    originalPrice: 170.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold", "Champagne", "Black"],
    sizes: ["Small"],
    rating: 4.9,
    reviewCount: 56,
    description: "Jeweled evening handbag featuring crystal clasp accent and detachable snake chain shoulder strap.",
    material: "Silk Satin, Crystal Clasp",
    careInstructions: "Store in protective dustbag.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 605,
    name: "Florentine Calfskin Duffel Bag",
    category: "bags",
    gender: "unisex",
    price: 360.00,
    originalPrice: 450.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80"],
    colors: ["Espresso Brown", "Tan"],
    sizes: ["Weekend Size"],
    rating: 5.0,
    reviewCount: 71,
    description: "Luxurious weekend travel holdall with brass hardware, detachable padded strap, and shoe compartment.",
    material: "100% Florentine Calfskin",
    careInstructions: "Apply leather wax annual.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 606,
    name: "Woven Straw Summer Beach Bag",
    category: "bags",
    gender: "women",
    price: 110.00,
    originalPrice: 140.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=800&auto=format&fit=crop&q=80"],
    colors: ["Natural Raffia / Tan Leather"],
    sizes: ["Large"],
    rating: 4.6,
    reviewCount: 34,
    description: "Handwoven raffia straw basket tote detailed with smooth leather handles and interior canvas drawstring bag.",
    material: "100% Natural Raffia Straw",
    careInstructions: "Avoid direct rain exposure.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 607,
    name: "Urban Leather City Backpack",
    category: "bags",
    gender: "unisex",
    price: 230.00,
    originalPrice: 290.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80"],
    colors: ["Matte Black", "Olive"],
    sizes: ["Medium"],
    rating: 4.8,
    reviewCount: 63,
    description: "Streamlined city backpack fitted with 15-inch padded laptop pocket and hidden anti-theft back zip.",
    material: "Waterproof Leather & Canvas",
    careInstructions: "Wipe with damp cloth.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 608,
    name: "Crescent Hobo Shoulder Bag",
    category: "bags",
    gender: "women",
    price: 210.00,
    originalPrice: 260.00,
    discount: 19,
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80"],
    colors: ["Cream", "Black", "Terracotta"],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 41,
    description: "Trendy slouchy half-moon hobo bag crafted in buttery-soft calf leather with magnetic top seal.",
    material: "100% Soft Calfskin",
    careInstructions: "Condition leather as needed.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 609,
    name: "Micro Mini Leather Bucket Bag",
    category: "bags",
    gender: "women",
    price: 175.00,
    originalPrice: 220.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink", "Lilac", "Black"],
    sizes: ["Mini"],
    rating: 4.5,
    reviewCount: 28,
    description: "Cute drawstring bucket pouch with top carry handle and detachable chain strap.",
    material: "Smooth Nappa Leather",
    careInstructions: "Store in dustbag.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 610,
    name: "Crocodile-Embossed Leather Satchel",
    category: "bags",
    gender: "women",
    price: 280.00,
    originalPrice: 350.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80"],
    colors: ["Deep Emerald", "Burgundy"],
    sizes: ["Medium"],
    rating: 4.9,
    reviewCount: 65,
    description: "Elegant top-handle structured handbag with crocodile embossing and golden feet studs.",
    material: "Croc-Embossed Italian Leather",
    careInstructions: "Wipe clean with cloth.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },

  // ==================== 7. SHOES (10 items) ====================
  {
    id: 701,
    name: "Minimalist Italian Leather Heel",
    category: "shoes",
    gender: "women",
    price: 195.00,
    originalPrice: 250.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold", "Nude Pink", "Onyx"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.8,
    reviewCount: 51,
    description: "Sleek 75mm stiletto heels handcrafted in Florence with cushioned leather footbed for effortless elegance.",
    material: "Italian Calf Leather",
    careInstructions: "Store in protective dustbag.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 702,
    name: "Minimalist Suede Sneakers",
    category: "shoes",
    gender: "unisex",
    price: 155.00,
    originalPrice: 195.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Pink / White", "Off-White / Beige"],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    rating: 4.8,
    reviewCount: 84,
    description: "Low-top cupsole sneaker with premium suede upper, leather lining, and durable natural rubber outsole.",
    material: "Italian Calf Suede, Rubber Outsole",
    careInstructions: "Use suede protector spray prior to wear.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 703,
    name: "Pointed-Toe Leather Ankle Boots",
    category: "shoes",
    gender: "women",
    price: 225.00,
    originalPrice: 280.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black", "Cognac Brown"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.9,
    reviewCount: 62,
    description: "Chic leather booties designed with a sharp pointed toe, block heel, and side zip closure.",
    material: "Full-Grain Italian Calfskin",
    careInstructions: "Polished leather care.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 704,
    name: "Penny Loafer Calfskin Shoes",
    category: "shoes",
    gender: "men",
    price: 185.00,
    originalPrice: 230.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80"],
    colors: ["Espresso", "Black"],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.7,
    reviewCount: 45,
    description: "Hand-stitched leather penny loafers featuring Goodyear welted leather sole and cushioned insoles.",
    material: "100% Genuine Calfskin",
    careInstructions: "Polish with neutral wax.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 705,
    name: "Strappy Satin Stiletto Sandals",
    category: "shoes",
    gender: "women",
    price: 180.00,
    originalPrice: 225.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold", "Emerald Green", "Silver"],
    sizes: ["36", "37", "38", "39"],
    rating: 4.8,
    reviewCount: 39,
    description: "Bespoke evening heels styled with delicate criss-cross ankle straps and 90mm slim heel.",
    material: "Silk Satin Upper, Leather Sole",
    careInstructions: "Avoid wet surface contact.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 706,
    name: "Classic Leather Oxford Dress Shoes",
    category: "shoes",
    gender: "men",
    price: 240.00,
    originalPrice: 300.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80"],
    colors: ["Polished Black", "Chestnut"],
    sizes: ["40", "41", "42", "43", "44"],
    rating: 4.9,
    reviewCount: 57,
    description: "Formal closed-lacing Oxford shoes handcrafted with cap-toe detail and Goodyear welted sole.",
    material: "Full-Grain Italian Calfskin",
    careInstructions: "Buff with horsehair brush.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 707,
    name: "Suede Chelsea Ankle Boots",
    category: "shoes",
    gender: "unisex",
    price: 210.00,
    originalPrice: 260.00,
    discount: 19,
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Sand Suede", "Charcoal Suede"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    rating: 4.7,
    reviewCount: 48,
    description: "Timeless Chelsea boots with twin elastic side gussets and pull tabs for easy slip-on fit.",
    material: "Italian Calf Suede",
    careInstructions: "Brush gently with suede brush.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 708,
    name: "Chunky Leather Platform Boots",
    category: "shoes",
    gender: "women",
    price: 235.00,
    originalPrice: 295.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black Leather"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.8,
    reviewCount: 53,
    description: "Edgy combat boots featuring lugged platform rubber sole and lace-up front with side zip.",
    material: "Nappa Leather, Rubber Sole",
    careInstructions: "Clean with damp cloth.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 709,
    name: "Woven Leather Summer Mules",
    category: "shoes",
    gender: "women",
    price: 165.00,
    originalPrice: 210.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=800&auto=format&fit=crop&q=80"],
    colors: ["Tan Leather", "Ivory"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.6,
    reviewCount: 27,
    description: "Pointed slip-on mules handwoven in supple soft leather with a low block stacked heel.",
    material: "Handwoven Lambskin",
    careInstructions: "Store in dustbag.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 710,
    name: "Casual Canvas Low-Top Trainers",
    category: "shoes",
    gender: "unisex",
    price: 85.00,
    originalPrice: 110.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80"],
    colors: ["Off-White", "Black Canvas"],
    sizes: ["37", "38", "39", "40", "41", "42", "43"],
    rating: 4.5,
    reviewCount: 66,
    description: "Retro canvas low-top sneakers with vulcanized rubber sole and comfortable cushioned arch support.",
    material: "100% Organic Canvas",
    careInstructions: "Hand wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },

  // ==================== 8. ACCESSORIES (10 items) ====================
  {
    id: 801,
    name: "Chrono Gold Rose Wristwatch",
    category: "accessories",
    gender: "unisex",
    price: 210.00,
    originalPrice: 260.00,
    discount: 19,
    images: ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold / White", "Silver / Black"],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 115,
    description: "Minimalist timepiece featuring Japanese quartz movement, sapphire crystal glass, and genuine Italian leather strap.",
    material: "Stainless Steel Case, Sapphire Glass",
    careInstructions: "30m Water Resistant.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 802,
    name: "Cat-Eye Acetate Sunglasses",
    category: "accessories",
    gender: "women",
    price: 95.00,
    originalPrice: 130.00,
    discount: 26,
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80"],
    colors: ["Blush Tortoise", "Black", "Translucent Pink"],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 63,
    description: "Hand-polished acetate frames equipped with 100% UV400 polarized lenses for total glare protection.",
    material: "Handmade Acetate",
    careInstructions: "Clean with microfiber cloth provided.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 803,
    name: "Silk Floral Bandana Scarf",
    category: "accessories",
    gender: "women",
    price: 65.00,
    originalPrice: 85.00,
    discount: 23,
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80"],
    colors: ["Pink Peony", "Ivory Blossom"],
    sizes: ["65x65cm"],
    rating: 4.8,
    reviewCount: 38,
    description: "Hand-rolled edge square silk scarf printed with bespoke floral motifs.",
    material: "100% Silk Twill",
    careInstructions: "Dry clean or hand wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 804,
    name: "Pearl & Rose Gold Drop Earrings",
    category: "accessories",
    gender: "women",
    price: 115.00,
    originalPrice: 145.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Gold"],
    sizes: ["One Size"],
    rating: 5.0,
    reviewCount: 77,
    description: "Freshwater cultured pearls suspended from 18k rose gold plated sterling silver posts.",
    material: "Freshwater Pearl, 18k Rose Gold Vermeil",
    careInstructions: "Avoid contact with perfumes and water.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 805,
    name: "Slim Bifold Leather Wallet",
    category: "accessories",
    gender: "men",
    price: 75.00,
    originalPrice: 95.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80"],
    colors: ["Burgundy", "Espresso", "Black"],
    sizes: ["One Size"],
    rating: 4.6,
    reviewCount: 40,
    description: "RFID-blocking slim bifold wallet featuring 8 card slots and dual bill compartments.",
    material: "Vegetable-Tanned Calfskin",
    careInstructions: "Wipe with damp cloth.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 806,
    name: "Layered Gold Coin Necklace",
    category: "accessories",
    gender: "women",
    price: 88.00,
    originalPrice: 110.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80"],
    colors: ["18k Gold Plated"],
    sizes: ["Adjustable Chain"],
    rating: 4.8,
    reviewCount: 54,
    description: "Double-chain necklace featuring vintage embossed coin pendant cast in 18k gold vermeil.",
    material: "18k Gold Plated Sterling Silver",
    careInstructions: "Store in jewelry pouch.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 807,
    name: "Minimalist Italian Leather Belt",
    category: "accessories",
    gender: "unisex",
    price: 70.00,
    originalPrice: 90.00,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&auto=format&fit=crop&q=80"],
    colors: ["Black Gold Buckle", "Tan Silver Buckle"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 43,
    description: "Sleek 30mm full-grain leather belt finished with polished solid brass buckle.",
    material: "100% Full-Grain Leather",
    careInstructions: "Wipe with leather conditioner.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 808,
    name: "Chunky Gold Hoop Earrings",
    category: "accessories",
    gender: "women",
    price: 60.00,
    originalPrice: 80.00,
    discount: 25,
    images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80"],
    colors: ["18k Yellow Gold"],
    sizes: ["Medium"],
    rating: 4.9,
    reviewCount: 82,
    description: "Lightweight hollow tube hoop earrings plated in 18k yellow gold with secure latch back.",
    material: "18k Gold Vermeil",
    careInstructions: "Avoid harsh chemicals.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 809,
    name: "Polarized Aviator Sunglasses",
    category: "accessories",
    gender: "unisex",
    price: 110.00,
    originalPrice: 140.00,
    discount: 21,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80"],
    colors: ["Gold Frame / Dark Green Lens"],
    sizes: ["One Size"],
    rating: 4.8,
    reviewCount: 59,
    description: "Classic metal aviator sunglasses equipped with scratch-resistant polarized lenses.",
    material: "Stainless Steel Frame, Glass Lens",
    careInstructions: "Clean with cloth.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 810,
    name: "Pure Silk Sleep Eye Mask",
    category: "accessories",
    gender: "unisex",
    price: 40.00,
    originalPrice: 50.00,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1616867623916-24876b5d92df?w=800&auto=format&fit=crop&q=80"],
    colors: ["Rose Soft", "Champagne", "Midnight Black"],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 91,
    description: "Ultra-soft padded Mulberry silk eye mask for soothing skin and complete light blockout.",
    material: "100% 22 Momme Silk",
    careInstructions: "Hand wash cold.",
    featured: true,
    newArrival: true,
    bestSeller: false
  }
];
