/**
 * ÉLÉGANCE - FASHION E-COMMERCE PRODUCT DATASET
 * 20 Premium Realistic Demo Fashion Products with High-Res Unsplash Photography
 */

const PRODUCTS_DATA = [
  {
    id: 101,
    name: "Silk Wrap Midi Dress",
    category: "dresses",
    gender: "women",
    price: 189.00,
    originalPrice: 240.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Blush Pink", "Midnight Black", "Champagne"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviewCount: 42,
    description: "Tailored from 100% pure mulberry silk, this wrap dress features an asymmetric drape, defined waist tie, and elegant midi hemline perfect for evening occasions.",
    material: "100% Mulberry Silk",
    careInstructions: "Dry clean only. Cool iron on reverse.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 102,
    name: "Cashmere Oversized Sweater",
    category: "knitwear",
    gender: "women",
    price: 145.00,
    originalPrice: 185.00,
    discount: 22,
    images: [
      "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Rose Soft", "Off White", "Camel"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviewCount: 68,
    description: "Luxuriously soft Mongolian cashmere knit sweater with a relaxed crew neck and ribbed trim accents.",
    material: "100% Mongolian Cashmere",
    careInstructions: "Hand wash cold with wool detergent. Lay flat to dry.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 103,
    name: "Tailored Double-Breasted Blazer",
    category: "outerwear",
    gender: "women",
    price: 220.00,
    originalPrice: 280.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Powder Pink", "Ivory", "Classic Navy"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviewCount: 29,
    description: "Structured wool-blend blazer featuring horn buttons, sharp lapels, and functional flap pockets.",
    material: "70% Wool, 30% Silk Blend",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 104,
    name: "High-Waisted Pleated Trousers",
    category: "pants",
    gender: "women",
    price: 110.00,
    originalPrice: 140.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Dusty Rose", "Cream", "Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 35,
    description: "Flowy wide-leg trousers designed with front darts, high rise, and concealed front zip closure.",
    material: "95% Crepe Viscose, 5% Elastane",
    careInstructions: "Machine wash cold gentle cycle.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 105,
    name: "Quilted Leather Shoulder Bag",
    category: "bags",
    gender: "women",
    price: 290.00,
    originalPrice: 350.00,
    discount: 17,
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Blush Pink", "Black Gold", "Taupe"],
    sizes: ["One Size"],
    rating: 5.0,
    reviewCount: 88,
    description: "Handcrafted calfskin leather handbag with gold chain strap, twist lock closure, and micro-suede interior lining.",
    material: "100% Genuine Nappa Leather",
    careInstructions: "Wipe clean with soft leather conditioner.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 106,
    name: "Minimalist Italian Leather Heel",
    category: "shoes",
    gender: "women",
    price: 195.00,
    originalPrice: 250.00,
    discount: 22,
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Rose Gold", "Nude Pink", "Onyx"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.8,
    reviewCount: 51,
    description: "Sleek 75mm stiletto heels handcrafted in Florence with cushioned leather footbed for effortless elegance.",
    material: "Italian Calf Leather",
    careInstructions: "Store in protective dustbag.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 107,
    name: "Classic Wool Trench Coat",
    category: "outerwear",
    gender: "men",
    price: 275.00,
    originalPrice: 350.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Beige", "Black", "Charcoal"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
    reviewCount: 31,
    description: "Timeless double-breasted trench coat with waist belt, epaulettes, and weather-resistant wool gabardine.",
    material: "100% Virgin Wool",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 108,
    name: "Slim Fit Oxford Cotton Shirt",
    category: "shirts",
    gender: "men",
    price: 85.00,
    originalPrice: 110.00,
    discount: 22,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Soft Pink", "Light Blue", "Crisp White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 94,
    description: "Breathable organic cotton oxford shirt tailored with button-down collar and mother-of-pearl buttons.",
    material: "100% Organic Cotton",
    careInstructions: "Machine wash warm, tumble dry low.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 109,
    name: "Structured Italian Linen Suit Jacket",
    category: "jackets",
    gender: "men",
    price: 310.00,
    originalPrice: 390.00,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Dusty Pink", "Sand", "Navy"],
    sizes: ["38R", "40R", "42R", "44R"],
    rating: 4.8,
    reviewCount: 22,
    description: "Lightweight unstructured linen jacket tailored with notch lapels, double vents, and satin lining.",
    material: "100% Italian Linen",
    careInstructions: "Dry clean only.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 110,
    name: "Merino Wool Crewneck Sweater",
    category: "knitwear",
    gender: "men",
    price: 125.00,
    originalPrice: 160.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Rosewood", "Grey Melange", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 47,
    description: "Extra-fine merino wool pullover offering thermal comfort, ribbed cuffs, and sophisticated texture.",
    material: "100% Extra-fine Merino Wool",
    careInstructions: "Hand wash cold, dry flat.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 111,
    name: "Chrono Gold Rose Wristwatch",
    category: "accessories",
    gender: "unisex",
    price: 210.00,
    originalPrice: 260.00,
    discount: 19,
    images: [
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Rose Gold / White", "Silver / Black"],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 115,
    description: "Minimalist timepiece featuring Japanese quartz movement, sapphire crystal glass, and genuine Italian leather strap.",
    material: "Stainless Steel Case, Sapphire Glass",
    careInstructions: "30m Water Resistant.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 112,
    name: "Cat-Eye Acetate Sunglasses",
    category: "accessories",
    gender: "women",
    price: 95.00,
    originalPrice: 130.00,
    discount: 26,
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Blush Tortoise", "Black", "Translucent Pink"],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 63,
    description: "Hand-polished acetate frames equipped with 100% UV400 polarized lenses for total glare protection.",
    material: "Handmade Acetate",
    careInstructions: "Clean with microfiber cloth provided.",
    featured: false,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 113,
    name: "Silk Floral Bandana Scarf",
    category: "accessories",
    gender: "women",
    price: 65.00,
    originalPrice: 85.00,
    discount: 23,
    images: [
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Pink Peony", "Ivory Blossom"],
    sizes: ["65x65cm"],
    rating: 4.8,
    reviewCount: 38,
    description: "Hand-rolled edge square silk scarf printed with bespoke floral motifs.",
    material: "100% Silk Twill",
    careInstructions: "Dry clean or hand wash cold.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 114,
    name: "Pearl & Rose Gold Drop Earrings",
    category: "accessories",
    gender: "women",
    price: 115.00,
    originalPrice: 145.00,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Rose Gold"],
    sizes: ["One Size"],
    rating: 5.0,
    reviewCount: 77,
    description: "Freshwater cultured pearls suspended from 18k rose gold plated sterling silver posts.",
    material: "Freshwater Pearl, 18k Rose Gold Vermeil",
    careInstructions: "Avoid contact with perfumes and water.",
    featured: true,
    newArrival: true,
    bestSeller: true
  },
  {
    id: 115,
    name: "Minimalist Leather Tote Bag",
    category: "bags",
    gender: "women",
    price: 240.00,
    originalPrice: 300.00,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Soft Rose", "Caramel", "Black"],
    sizes: ["Large"],
    rating: 4.8,
    reviewCount: 92,
    description: "Spacious everyday tote with laptop sleeve, magnetic closure, and reinforced shoulder straps.",
    material: "Full-Grain Italian Leather",
    careInstructions: "Condition regularly.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 116,
    name: "Slim Bifold Leather Wallet",
    category: "accessories",
    gender: "men",
    price: 75.00,
    originalPrice: 95.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Burgundy", "Espresso", "Black"],
    sizes: ["One Size"],
    rating: 4.6,
    reviewCount: 40,
    description: "RFID-blocking slim bifold wallet featuring 8 card slots and dual bill compartments.",
    material: "Vegetable-Tanned Calfskin",
    careInstructions: "Wipe with damp cloth.",
    featured: false,
    newArrival: false,
    bestSeller: false
  },
  {
    id: 117,
    name: "Satin Evening Slip Dress",
    category: "dresses",
    gender: "women",
    price: 165.00,
    originalPrice: 210.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Magenta", "Emerald", "Champagne"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 54,
    description: "Floor-sweeping bias-cut satin gown with cowled neckline and adjustable delicate shoulder straps.",
    material: "97% Polyester Satin, 3% Elastane",
    careInstructions: "Hand wash cold or dry clean.",
    featured: true,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 118,
    name: "Cropped Denim Jacket",
    category: "outerwear",
    gender: "women",
    price: 130.00,
    originalPrice: 160.00,
    discount: 18,
    images: [
      "https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Vintage Wash", "Light Pink Wash"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviewCount: 33,
    description: "Classic trucker style cropped jacket cut from rigid organic cotton denim with custom branded shank buttons.",
    material: "100% Organic Denim",
    careInstructions: "Machine wash cold inside out.",
    featured: false,
    newArrival: true,
    bestSeller: false
  },
  {
    id: 119,
    name: "Chino Slim Fit Stretch Pants",
    category: "pants",
    gender: "men",
    price: 98.00,
    originalPrice: 125.00,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Stone Beige", "Dusty Pink", "Navy"],
    sizes: ["30", "32", "34", "36"],
    rating: 4.7,
    reviewCount: 61,
    description: "Versatile stretch-twill chinos engineered for maximum movement and sharp tailored silhouette.",
    material: "98% Cotton, 2% Elastane",
    careInstructions: "Machine wash cold with like colors.",
    featured: false,
    newArrival: false,
    bestSeller: true
  },
  {
    id: 120,
    name: "Minimalist Suede Sneakers",
    category: "shoes",
    gender: "unisex",
    price: 155.00,
    originalPrice: 195.00,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80"
    ],
    colors: ["Blush Pink / White", "Off-White / Beige"],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    rating: 4.8,
    reviewCount: 84,
    description: "Low-top cupsole sneaker with premium suede upper, leather lining, and durable natural rubber outsole.",
    material: "Italian Calf Suede, Rubber Outsole",
    careInstructions: "Use suede protector spray prior to wear.",
    featured: true,
    newArrival: false,
    bestSeller: true
  }
];
